### ISSUE TITLE
How to update Mautic

### ISSUE THREAD

**Issue by fakela** [mautic/user-documentation#20]
https://docs.mautic.org/en/setup/how-to-update-mautic

**Comment by favour-chibueze** [comment]
@fakela Can I own this one?

**Comment by fakela** [comment]
> @fakela Can I own this one?

Yeah 👍

**Comment by pragatijain** [comment]
@fakela @favour-chibueze I am reviewing Updating Mautic in the browser page and have already submitted Updating Mautic  Using CLI. I can own this page also if @favour-chibueze is ok about it and has not started working on it.

**Comment by fakela** [comment]
@pragatijain How to update mautic is written already but in `.md`. As we are moving the docs to `rst` it's not visible yet.

**Comment by fakela** [comment]
> @fakela @favour-chibueze I am reviewing Updating Mautic in the browser page and have already submitted Updating Mautic Using CLI. I can own this page also if @favour-chibueze is ok about it and has not started working on it.

I will check out the new submission you made

**Comment by RCheesley** [comment]
Hey folks! The files were in the wrong places so I have moved them to where they should be and sorted out the rst conversion with #33. I combined the updating resources into one file with the headings so that they create the appropriate nesting in the menu:

![image](https://user-images.githubusercontent.com/2930593/161261345-76b68eea-e9a0-411a-94f8-54dd63680cbc.png)

The headings to use for the indentation to work:

```
Heading 1
########

Heading 2
**********

Heading 3
========

Heading 4
~~~~~~~~
```

**Comment by RCheesley** [comment]
Closing as this one has been merged.
